// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.BackApp.Domain;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240305232731_addSoltUserPassword")]
    partial class addSoltUserPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.BackApp.Domain.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("494a1eda-dc67-46d1-be1e-603ff9300078"),
                            DataCreate = new DateTime(2024, 2, 20, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 24, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Name = "Category1"
                        },
                        new
                        {
                            Id = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 2, 20, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 24, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Name = "Category2"
                        },
                        new
                        {
                            Id = new Guid("2315de19-70c6-43f1-b845-171f3acaa609"),
                            DataCreate = new DateTime(2024, 2, 20, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 24, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Name = "Category3"
                        },
                        new
                        {
                            Id = new Guid("531b4dfc-8372-48f9-92bf-56132faaab4b"),
                            CategoryId = new Guid("494a1eda-dc67-46d1-be1e-603ff9300078"),
                            DataCreate = new DateTime(2024, 2, 20, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 24, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Name = "Category4"
                        },
                        new
                        {
                            Id = new Guid("59b99baa-e1d0-44f6-9c73-959bc26ff33a"),
                            CategoryId = new Guid("531b4dfc-8372-48f9-92bf-56132faaab4b"),
                            DataCreate = new DateTime(2024, 2, 20, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 24, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Name = "Category5"
                        });
                });

            modelBuilder.Entity("Shop.BackApp.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c760b5a-c932-46d1-b644-6421a90cc5bc"),
                            CategoryId = new Guid("59b99baa-e1d0-44f6-9c73-959bc26ff33a"),
                            DataCreate = new DateTime(2024, 2, 29, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 3, 3, 9, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Burns for 10 hours",
                            Name = "Lamp",
                            Price = 11.11m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("355f327b-77f9-47a3-945a-3a931dfab0d5"),
                            CategoryId = new Guid("2315de19-70c6-43f1-b845-171f3acaa609"),
                            DataCreate = new DateTime(2024, 3, 3, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 29, 14, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Rubber under your foot",
                            Name = "Slippers",
                            Price = 11.11m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("03d30802-1729-4fdd-9fbe-1c15a3366112"),
                            CategoryId = new Guid("494a1eda-dc67-46d1-be1e-603ff9300078"),
                            DataCreate = new DateTime(2024, 3, 4, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 3, 4, 22, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description1",
                            Name = "Name1",
                            Price = 1.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("fce0c66a-d178-4f96-9372-ede93134ca5b"),
                            CategoryId = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 3, 3, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 3, 3, 21, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description2",
                            Name = "Name2",
                            Price = 2.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("0f844933-a168-468c-ac39-e0f1cb9d7488"),
                            CategoryId = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 3, 2, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 3, 2, 20, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description3",
                            Name = "Name3",
                            Price = 3.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("27ecbd06-d10c-4398-9af5-827b2cf092a3"),
                            CategoryId = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 3, 1, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 3, 1, 19, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description4",
                            Name = "Name4",
                            Price = 4.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("2352f267-1bd1-45a0-8843-6fffc3616c88"),
                            CategoryId = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 2, 29, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 29, 18, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description5",
                            Name = "Name5",
                            Price = 5.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("9a6eb998-b038-43e0-a44c-69c195b0a294"),
                            CategoryId = new Guid("531b4dfc-8372-48f9-92bf-56132faaab4b"),
                            DataCreate = new DateTime(2024, 2, 28, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 28, 17, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description6",
                            Name = "Name6",
                            Price = 6.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("2fe6a181-5d33-4902-8990-e764330c451f"),
                            CategoryId = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 2, 27, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 27, 16, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description7",
                            Name = "Name7",
                            Price = 7.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        },
                        new
                        {
                            Id = new Guid("2dc4ff7f-9297-4e90-9b5b-25bc5c66a382"),
                            CategoryId = new Guid("81402a0d-5d0a-4945-b0c6-828e649b1ead"),
                            DataCreate = new DateTime(2024, 2, 26, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 28, 15, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Description = "Description8",
                            Name = "Name8",
                            Price = 8.99m,
                            UserId = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11")
                        });
                });

            modelBuilder.Entity("Shop.BackApp.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc7b21e3-fa55-40c3-8ba5-dd36b1acbb11"),
                            DataCreate = new DateTime(2024, 2, 19, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            DataUpdate = new DateTime(2024, 2, 24, 23, 27, 31, 31, DateTimeKind.Utc).AddTicks(5385),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = "eBeztJdRYQgfaYk47pPS59MJmHfqx40KowgYJ4OBx4M=",
                            PasswordSalt = "MtJZfRGlZgXM0Kda8OGLlw=="
                        });
                });

            modelBuilder.Entity("Shop.BackApp.Domain.Entity.Category", b =>
                {
                    b.HasOne("Shop.BackApp.Domain.Entity.Category", null)
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Shop.BackApp.Domain.Entity.Category", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
