// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Domain;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240225083627_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Domain.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40ec11f6-298d-436b-a388-58012771d7b2"),
                            DataCreate = new DateTime(2024, 2, 11, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 15, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Name = "Category1"
                        },
                        new
                        {
                            Id = new Guid("3737017f-955c-4935-a358-201e760eecb2"),
                            DataCreate = new DateTime(2024, 2, 11, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 15, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Name = "Category2"
                        },
                        new
                        {
                            Id = new Guid("25a28334-238a-4130-ba37-3118318f264c"),
                            DataCreate = new DateTime(2024, 2, 11, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 15, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Name = "Category3"
                        },
                        new
                        {
                            Id = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            CategoryId = new Guid("40ec11f6-298d-436b-a388-58012771d7b2"),
                            DataCreate = new DateTime(2024, 2, 11, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 15, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Name = "Category4"
                        },
                        new
                        {
                            Id = new Guid("cc32089e-ce20-4687-9634-8a01594979f2"),
                            CategoryId = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            DataCreate = new DateTime(2024, 2, 11, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 15, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Name = "Category5"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c24806a8-ad36-4368-893b-ab8ab8665f3a"),
                            CategoryId = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            DataCreate = new DateTime(2024, 2, 20, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 22, 18, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Burns for 10 hours",
                            Name = "Lamp",
                            Price = 11.11m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("7a12d90d-a0cc-41b0-9b2f-fe4c5ef362be"),
                            CategoryId = new Guid("3737017f-955c-4935-a358-201e760eecb2"),
                            DataCreate = new DateTime(2024, 2, 23, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 19, 23, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Rubber under your foot",
                            Name = "Slippers",
                            Price = 11.11m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("8fba70de-0948-4f2b-bdfe-1cece9b13cfb"),
                            CategoryId = new Guid("25a28334-238a-4130-ba37-3118318f264c"),
                            DataCreate = new DateTime(2024, 2, 24, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 24, 7, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description1",
                            Name = "Name1",
                            Price = 1.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("043c008b-c8d9-43db-8d2a-3319433c774d"),
                            CategoryId = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            DataCreate = new DateTime(2024, 2, 23, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 23, 6, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description2",
                            Name = "Name2",
                            Price = 2.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("0f17821f-f271-4da7-89e9-0f4730e40ddd"),
                            CategoryId = new Guid("25a28334-238a-4130-ba37-3118318f264c"),
                            DataCreate = new DateTime(2024, 2, 22, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 22, 5, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description3",
                            Name = "Name3",
                            Price = 3.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("2b52a61d-c404-49fe-834d-9ac8423a1b23"),
                            CategoryId = new Guid("3737017f-955c-4935-a358-201e760eecb2"),
                            DataCreate = new DateTime(2024, 2, 21, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 21, 4, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description4",
                            Name = "Name4",
                            Price = 4.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("617b47ce-cfe6-4e1d-8d80-ac6ead1cfd2d"),
                            CategoryId = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            DataCreate = new DateTime(2024, 2, 20, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 20, 3, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description5",
                            Name = "Name5",
                            Price = 5.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("f0208b36-ba13-4b82-8af2-9ad65649b98d"),
                            CategoryId = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            DataCreate = new DateTime(2024, 2, 19, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 19, 2, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description6",
                            Name = "Name6",
                            Price = 6.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("ac1baca8-ea79-47c4-b8e0-9a62683cfb90"),
                            CategoryId = new Guid("53dae8a2-dc28-4a10-8861-1bc246d6a993"),
                            DataCreate = new DateTime(2024, 2, 18, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 18, 1, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description7",
                            Name = "Name7",
                            Price = 7.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        },
                        new
                        {
                            Id = new Guid("8c39da73-d323-4f99-a6b2-3f8a491825a9"),
                            CategoryId = new Guid("40ec11f6-298d-436b-a388-58012771d7b2"),
                            DataCreate = new DateTime(2024, 2, 17, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 19, 0, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Description = "Description8",
                            Name = "Name8",
                            Price = 8.99m,
                            UserId = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc")
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("983efc4b-93e9-4814-bdce-3245204f1dbc"),
                            DataCreate = new DateTime(2024, 2, 10, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            DataUpdate = new DateTime(2024, 2, 15, 8, 36, 26, 762, DateTimeKind.Utc).AddTicks(2621),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entity.Category", b =>
                {
                    b.HasOne("Shop.Domain.Entity.Category", null)
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Shop.Domain.Entity.Category", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
