// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Domain;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240219211518_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d89cfa2-f4f9-40a4-9db6-d656f6283ff4"),
                            DataCreate = new DateTime(2024, 2, 14, 21, 15, 18, 333, DateTimeKind.Utc).AddTicks(8506),
                            DataUpdate = new DateTime(2024, 2, 17, 7, 15, 18, 333, DateTimeKind.Utc).AddTicks(8506),
                            Description = "Burns for 10 hours",
                            Name = "Lamp",
                            Price = 11.11m
                        },
                        new
                        {
                            Id = new Guid("c3f97ab0-50ed-4810-81cf-0c3bd0db31ed"),
                            DataCreate = new DateTime(2024, 2, 17, 21, 15, 18, 333, DateTimeKind.Utc).AddTicks(8506),
                            DataUpdate = new DateTime(2024, 2, 14, 12, 15, 18, 333, DateTimeKind.Utc).AddTicks(8506),
                            Description = "Rubber under your foot",
                            Name = "Slippers",
                            Price = 11.11m
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e0e9e41-22d2-4956-bab5-099ea3f5b736"),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
